services:
  - type: web
    name: nocodb
    runtime: docker
    image:
      url: nocodb/nocodb:latest
    plan: starter   # kies desnoods een groter plan
    envVars:
      - key: NC_DB
        value: pg://dpg-d1le7u95pdvs73bsq8eg-a.frankfurt-postgres.render.com:5432?u=ailliaz&p=Uqzj3O5rnOAS0jgmC2lvmTkf10bJ3m7P&d=ailliaz_v14s
      - key: NC_AUTH_JWT_SECRET
        value: 8d3c0a56-09de-43a4-90f1-b3cb2c4af49f
    autoDeploy: true
